package:
  name: shiftx2
  version: 1.0.7

build:
  number: 2

source:
  url: http://www.shiftx2.ca/download/shiftx2-v107-linux-20120106.tgz
  fn: shiftx2-v107-linux-20120106.tgz

about:
  home: http://www.shiftx2.ca/
  license: All rights reserved
  summary: SHIFTX2 predicts both the backbone and side chain 1H, 13C and 15N chemical shifts for proteins using their structural (PDB) coordinates as input.